name: Github actions demo
run-name: ${{ github.actor }} is testing out github action
on: [push]
jobs:
  Explore-github-action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this job is triggered by ${{ github.event_name }}" event
      - run: echo "this job is running on ${{ runner.os }} server hosted by github"
      - run: echo "name of the branch is ${{ github.ref}} and repo is ${{ github.repository }}"
      - name: checkout repo code
        uses: actions/checkout@v4
      - run: echo "${{ github.repository }} repo has been cloned to the runner ${{ runner.os }}"
      - run: echo "the workflow is now ready to test your code on the runner"
      - name: list files in the repo
        run: |
              ls ${{ github.workspace }}
      - run: echo "the job status is ${{ job.status }}"

